#!/usr/bin/python3


from sys import stdin

l = stdin.readline()
ip = 0

tabsim = {}

print("#include <stdio.h>")
print("#include \"maq.h\"\n")


print("INSTR programa[] = { \n  {PUSH, 3}, \n  {PUSH, 6}, \n  {CALL, 5}, \n  {PRN,  0}, \n  {END,  0}, \n  {ADD,  0}, \n  {RET,  0} \n};\n")

print("INSTR prog[] = {")
while l:
    label = op = ""
    arg   = 0
    try:
        l = l[:l.index('#')]
    except:
        pass
    keys = l.split()
    if len(keys) > 0 and keys[0].endswith(":"):
        label = keys[0][:-1]              #jogando fora o ':'
        tabsim[label]=ip
        keys.pop(0)
    if len(keys) > 0:
        op = keys.pop(0)
    if len(keys) > 0:
        arg = keys.pop(0)
        if arg in tabsim:
            arg = tabsim[arg]
    if op != "":
        print("  {%s, %s},"%(op,arg))
    else:
        print("")
    l = stdin.readline()
    ip += 1
print("};")

print("")
print("int main(int ac, char **av) { \n Maquina *maq = cria_maquina(programa); \n Maquina *maq2 = cria_maquina(prog); \n exec_maquina(maq, 3);")
print(" exec_maquina(maq2, 40);\n puts(\"---\");\n exec_maquina(maq, 10);\n puts(\"---\");\n exec_maquina(maq2, 10000);\n destroi_maquina(maq);")
print(" destroi_maquina(maq2);\n return 0;\n}")

# Local variables:
# mode: python
# End:
