#!/usr/bin/python3
import pygame as pg
import fileinput

from math import *

pg.init()                                 # inicialização do

# altura e largura da arena, em células
H, W = 15,15

# largura da célula
l = 26
# altura da célula
L = 2*l/sqrt(3)

# cria a janela
scr = pg.display.set_mode((2*W*l+l,int(1.5*L*H+L/2)))
# só para simplificar, atualização da imagem
atu = pg.display.update


# pinta o fundo da janela
scr.fill((127,127,127))
atu()

def convert(i ,j):
    """
    Converte a coordenada (i,j) para a posição em pixels na janela
    """
    x = (1 + i%2)*l + 2*j*l
    y = 1.5*i*L + L
    return x,y

class Robô(pg.sprite.Sprite):
    """
    Representa um robo, possui uma imagem
    """
    def __init__(s, img):
        """
        Construtor, img é o nome do arquivo com a imagem
        """
        pg.sprite.Sprite.__init__(s)
        s.image = pg.image.load(img)
        s.rect = s.image.get_rect()

    def draw(s, i,j):
        """
        Desenha o robo na célula (i,j)
        """
        x, y = convert(i,j)

        # fronteiras do sprite
        l0,h0,l1,h1 = s.rect

        # corrije a posição de acordo com o tamanho do sprite
        s.rect.topleft = [x-l1/2,y-h1/2]
        # desenha
        scr.blit(s.image, s.rect)    

class cell:
    """
    Representa uma das células da arena
    """
    def __init__(s,i,j, terreno, cristais, base):
        """
        Construtor, i e j formam a coordenada
        """
        # Posição do centro
        s.cx, s.cy = convert(i,j)
        # Cor (pode ser passada para o construtor no futuro)
        if (base == 0): #se for base do exercito 1, celula azul
            s.cor = (0,0,200)
        elif (base == 1): #se for base do exercito 2, celula vermelha
            s.cor = (200,0,0)
        #se não for base, pinta de acordo com o tipo de terreno
        elif (terreno == 0):
            s.cor = (200,200,200)
        elif (terreno == 1):
            s.cor = (100,100,100)
        elif (terreno == 2):
            s.cor = (50,50,50)
        elif (terreno == 3):
            s.cor = (25,10,42)
        elif (terreno == 4):
            s.cor = (2,5,7)

        #se tiver cristais na celula, ela terá contorno rosa. pra saber se tem mais de um, vai ter que consultar
        if (cristais > 0):
            s.contorno = (243, 123, 173)
        else:
            s.contorno = (0,0,0)


        # Vértices do hexágono
        s.pontos = (
            (s.cx,   s.cy-L),
            (s.cx+l, s.cy-L/2),
            (s.cx+l, s.cy+L/2),
            (s.cx,   s.cy+L),
            (s.cx-l, s.cy+L/2),
            (s.cx-l, s.cy-L/2),
            )

    def draw(s) :
        """
        Desenha a célula
        """
        pg.draw.polygon(scr, s.cor, s.pontos, 0)
        pg.draw.lines(scr, s.contorno, True, s.pontos, 2)


# Construção da matriz que representa a arena
arena = []
for i in range(15):
    arena.append([])
    for j in range(15):
        arena[i].append(cell(i,j, 1, 0, -1))
        arena[i][j].draw()

# lista dos robos definidos
robs = []
#for i in range(3):
#    robs[i].append(robo(GILEAD_A.png))
#for j in range(4, 6):
#    robs[i].append(robo(GILEAD_B.png))

# atualiza a janela
atu()

# Leitura dos comandos pela entrada padrão ou de um arquivo
for line in fileinput.input():
    r = line.split()

    # linha começando com 'fim', termina o programa
    if r[0] == 'fim':
        break

    if r[0] == 'cel':
       arena[int(r[1])][int(r[2])] = cell(int(r[1]), int(r[2]), int(r[3]), int(r[4]), int(r[5]))
       arena[int(r[1])][int(r[2])].draw()
       continue

    # linha começando com 'rob', inclui um robo,
    # o segundo argumento na linha é a imagem
    if r[0] == 'rob':
        robs.append(Robô(r[1]))
        if 0 <= r[2]  < W and 0 <= r[3] < H and ri < len(robs):
            robs[ri].draw(r[2],r[3])
        continue

    # linha de movimentação:
    # robo, coordenadas originais, coordenadas finais
    ri, oi, oj, di, dj = list(map(int, r))

    # redesenha a célula original (apaga o robo)
    if 0 <= oi  < W and 0 <= oj < H:
        arena[oi][oj].draw()
    # desenha o robo na célula de destino
    if 0 <= di  < W and 0 <= dj < H and ri < len(robs):
        robs[ri].draw(di,dj)

    # tempo de espera para atualização, apenas para testes
    pg.time.wait(100)

    atu()

pg.quit()
# Local variables:
# mode: python
# End:
